# Generated by Django 4.2.15 on 2024-09-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizations',
            name='rating',
            field=models.CharField(blank=True, choices=[('Qoniqarsiz', 'Qoniqarsiz'), ("O'rtacha", "O'rtacha"), ('Yaxshi', 'Yaxshi')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='rating',
            field=models.CharField(blank=True, choices=[('Qoniqarsiz', 'Qoniqarsiz'), ("O'rtacha", "O'rtacha"), ('Yaxshi', 'Yaxshi')], max_length=16, null=True),
        ),
    ]
