# Generated by Django 4.2.15 on 2024-09-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_historicalorganizations_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='born_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='born_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
