# Generated by Django 4.2.15 on 2024-09-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_historicaluserprofile_manzil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='command_expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='command_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
